{% set name = "OpenMS" %}
{% set version = "3.4.1" %}  # if ends with 'dev' it is considered a development release and pulled from GitHub

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

{% if 'dev' in version %}
source:
  git_url: https://github.com/OpenMS/OpenMS.git
  git_rev: release/{{ version }}
  md5: unused
{% else %}
source:
  {% set version_parts = version.split('.') %}
  {% if version_parts|length == 3 and version_parts[2] == '0' %}
    {% set short_version = version_parts[0] ~ '.' ~ version_parts[1] %}
  {% else %}
    {% set short_version = version %}
  {% endif %}
  url: https://github.com/OpenMS/OpenMS/releases/download/release%2F{{ version }}/OpenMS-{{ short_version }}.tar.gz
  md5: 8d0b4d1d333f069959f7d5ff1c77a90f
{% endif %}

build:
  number: 1

requirements:
  # Shared build tools
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - sysroot_linux-64 =2.17  # [linux]
  # Shared host dependencies (used at link time)
  host:
    - qt6-main
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - xerces-c
    - libboost-devel
    - libboost
    - eigen >=3.4.0
    - hdf5
    - libsvm
    - coinmp
    - yaml-cpp
    - doxygen >=1.8.13
    - zlib
    - bzip2
    - apache-arrow-proc =*=cpu
    - libparquet
  # Shared runtime dependencies
  run:
    - libgomp  # [linux]
    - llvm-openmp  # [osx]

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

outputs:
  - name: libopenms
    version: {{ version }}
    script: package_libopenms.sh
    requirements:
      build:
        - cmake
        - sysroot_linux-64 =2.17  # [linux]
        - pkg-config
      host:
        # inherits from top-level
      run:
        # inherits from top-level
    build:
      run_exports:
        - {{ pin_compatible('llvm-openmp', max_pin='x.x') }}  # [osx]
        - {{ pin_compatible('zlib', max_pin='x.x') }}
        - {{ pin_compatible('xerces-c', max_pin='x.x') }}
        - {{ pin_compatible('eigen', max_pin='x.x') }}
        - {{ pin_compatible('hdf5', max_pin='x.x') }}
        - {{ pin_compatible('bzip2', max_pin='x.x') }}
        - {{ pin_compatible('qt6-main', max_pin='x.x') }}
        - {{ pin_compatible('libsvm', max_pin='x.x') }}
        - {{ pin_compatible('coinmp', max_pin='x.x') }}
        - libopenms {{ version }}

  - name: openms
    version: {{ version }}
    script: package_openms-tools.sh
    requirements:
      build:
        - cmake
        - sysroot_linux-64 =2.17  # [linux]
        - pkg-config
      host:
        - {{ pin_subpackage('libopenms', exact=True) }}
      run:
        - {{ pin_subpackage('libopenms', exact=True) }}
    test:
      commands:
        - OPENMS_DATA_PATH=${PREFIX}/share/OpenMS/ ${PREFIX}/bin/OpenMSInfo
        - OPENMS_DATA_PATH=${PREFIX}/share/OpenMS/ ${PREFIX}/bin/FileMerger --help

  - name: openms-thirdparty
    version: {{ version }}
    build:
      skip: True  # [osx]
    requirements:
      host:
        - {{ pin_subpackage('openms', exact=True) }}
      run:
        - {{ pin_subpackage('openms', exact=True) }}
        - comet-ms ==2024011
        - luciphor2 ==2020_04_03
        - msgf_plus ==2024.03.26
        - percolator ==3.7.1
        - sirius-ms >=6.1.0
        - thermorawfileparser ==1.4.3
        - sage-proteomics ==0.14.7
        - gnuplot
        - r-gplots
    test:
      commands:
        - OPENMS_DATA_PATH=${PREFIX}/share/OpenMS/ ${PREFIX}/bin/OpenMSInfo

about:
  home: "https://github.com/OpenMS/OpenMS"
  license: "BSD-3-Clause"
  license_family: BSD
  license_file: LICENSE
  summary: "OpenMS is an open-source software C++ library for LC-MS data management and analyses."
  dev_url: "https://github.com/OpenMS/OpenMS"
  doc_url: "https://openms.readthedocs.io/en/latest/index.html"

extra:
  additional-platforms:
    - linux-aarch64
  skip-lints:
    - build_number_needs_reset
    - missing_run_exports
    {% if 'dev' in version %}
    - uses_vcs_url
    {% endif %}
  identifiers:
    - biotools:openms
    - usegalaxy-eu:openms_fileconverter
    - doi:10.1038/nmeth.3959
