python:
  - 3.9.*  *_cpython
  - 3.10.*  *_cpython
  - 3.11.*  *_cpython
python_impl:
  - cpython
  - cpython
  - cpython
numpy:
  - 1.19.*
  - 1.19.*
  - 1.19.*  
zip_keys:
  - python
  - python_impl
  - numpy
