{% set name = "pyopenms" %}
{% set version = "2.8.0dev" %}
package:
  name: {{ name|lower  }}
  version: {{ version  }}

source:
  git_url: https://github.com/OpenMS/OpenMS.git
  git_rev: develop
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  skip: True  # [py2k]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake
  host:
    - libopenms {{ version }}
    - llvm-openmp # [osx]
    - libsvm
    - xerces-c
    - boost-cpp
    - qt
    - python {{ python }}
    - cython >=0.25.2
    - autowrap >=0.22.6
    - setuptools
    - wheel
    - pip
    - nose
    - numpy {{ numpy }}
    - pandas
  run: # run_exports in libopenms should take care of the libraries. But it does not because of bugs. So copy everthing again and again
    - libopenms {{ version }}
    - llvm-openmp # [osx]
    - libsvm
    - xerces-c
    - boost-cpp
    - qt
    - python {{ python }}
    - numpy {{ numpy }}
    - pandas
test:
  requires:
    - nose
  commands:
    - python -c "import pyopenms; print(pyopenms.__version__)"
    # We cant use the PYTHON variable since it does not exist on the biocontainer?!
    # TODO run the test suite

about:
  home: https://github.com/OpenMS/OpenMS
  license: BSD
  license_file: LICENSE
  summary: python bindings for OpenMS, an open-source software C++ library for LC-MS data management and analyses

extra:
  skip-lints:
    - build_number_needs_reset  # our linter has some issues with multi-package recipes as it seems
    - uses_vcs_url  # only for nightly builds
    - missing_hash  # only for nightly builds
  identifiers:
    - biotools:openms
    - doi:10.1038/nmeth.3959
